name: API and Web UI Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-test:
    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v4

    # setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.6.1

    # setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew

    # execute gradlew command for running API cucumber test
    - name: Execute Test
      run: ./gradlew cucumberApiTests

    # execute gradlew command for running Web UI cucumber test
    - name: Execute Test
      run: ./gradlew cucumberWebTests
